# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- azure-pipelines 

jobs:

- job: Linux
  pool: ubuntu-16.04

  steps:
  - script: echo Hello world
